// CommonJS mirror of voice.ts for the .cjs scripts in /scripts.
// Keep BANNED_PHRASES in sync with voice.ts. If you change one, change both.

const BANNED_PHRASES = [
  "leverage",
  "utilize",
  "optimize",
  "transformative",
  "cutting-edge",
  "seamless",
  "robust",
  "unlock",
  "unleash",
  "empower",
  "journey",
  "elevate",
  "delve",
  "embark",
  "disrupt",
  "blueprint",
  "innovative",
  "synergy",
  "stakeholders",
  "ecosystem",
  "alignment",
  "groundbreaking",
  "in conclusion",
  "let's explore",
  "let's be honest",
  "it's important to note",
  "it is worth noting",
  "the reality is",
  "here's the truth",
  "in today's fast-paced world",
  "in today's landscape",
  "at the end of the day",
  "moving forward",
  "circle back",
  "dive in",
  "dive deep",
  "navigate",
];

module.exports = { BANNED_PHRASES };
